name: ClOUD-RUN
on:
  workflow_dispatch:


permissions:
  id-token: write
  contents: read
  issues: write
  pull-requests: write

jobs:
  deploy_to_cloud_run:
    name: CLOUD-RUN-DEPLOY
    runs-on: ubuntu-latest
    steps:
      - name: Git Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: gradle

      - name: Install Dependencies
        run: ./gradlew build --no-daemon

      - name: Authenticate with GCP
        uses: google-github-actions/auth@v2
        with:
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_FEDERATION }}

      - name: Run Job
        run: |
          gcloud run deploy recommendations-job \
          --image asia-south1-docker.pkg.dev/architect-learning-435310/recommendations-engine/recommendations-pre-processor-job \
          --project ${{ secrets.PROJECT_ID }} \
          --platform managed \
          --region ${{ secrets.PROJECT_REGION }} \
          --args="${{ secrets.GCP_STORAGE_BUCKET_INPUT_PATH }}","${{ secrets.GCP_STORAGE_BUCKET_NAME }}"
          --set-env-vars DB_URL=${{ secrets.POSTGRES_DB_URL }},DB_USERNAME=${{ secrets.POSTGRES_DB_USERNAME }},DB_PASSWORD=${{ secrets.POSTGRES_DB_PASSWORD }},OUTPUT_PATH=${{ secrets.OUTPUT_PATH }}
      