name: ClOUD-RUN
on:
  workflow_dispatch:


permissions:
  id-token: write
  contents: read
  issues: write
  pull-requests: write

jobs:
  deploy_to_cloud_run:
    name: RUN PRE PROCESSOR JOB
    runs-on: ubuntu-latest
    steps:
      - name: Git Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: gradle

      - name: Install Dependencies
        run: ./gradlew build --no-daemon

      - name: Authenticate with GCP
        uses: google-github-actions/auth@v2
        with:
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_FEDERATION }}

      - name: Execute Cloud Run Job
        id: execute_job
        run: |
          EXECUTION_ID=$(gcloud beta run jobs execute ${{ secrets.JOB_NAME }} --region ${{ secrets.PROJECT_REGION }} --format="value(id)")
          echo "EXECUTION_ID=${EXECUTION_ID}" >> $GITHUB_ENV

      - name: Check Job Status
        id: check_status
        run: |
          STATUS=""
          while [[ "$STATUS" != "SUCCEEDED" && "$STATUS" != "FAILED" ]]; do
            STATUS=$(gcloud beta run jobs executions describe "${{ env.EXECUTION_ID }}" \
              --region asia-south1 --format="value(status.state)")
            echo "Current status: $STATUS"
            if [[ "$STATUS" == "FAILED" ]]; then
              echo "Job failed!"
              exit 1
            fi
            sleep 5
          done
          if [[ "$STATUS" != "SUCCEEDED" ]]; then
            echo "Job did not succeed!"
            exit 1
          fi

      - name: Notify Success
        if: success()
        run: echo "Job succeeded!"

      - name: Slack notification
        uses: 8398a7/action-slack@v3
        with:
          status: custom
          fields: workflow,job,commit,repo,ref,author,took
          custom_payload: |
            {
              attachments: [{
                color: '${{ job.status }}' === 'success' ? 'good' : '${{ job.status }}' === 'failure' ? 'danger' : 'warning',
                text: `Action Name: ${process.env.AS_WORKFLOW}\n Repository Name:${process.env.AS_REPO}@${process.env.AS_REF} by ${process.env.AS_AUTHOR} ${{ job.status }} in ${process.env.AS_TOOK}`,
              }]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        if: always()
